analysis_mode: "integration"
input_dirs:
  - "/home/joon/dev/critical_analyzer/data/Presentation"
  - "/home/joon/dev/critical_analyzer/data/Proposal"
final_prompt_path: "prompts/integration/document_integration.txt"
feedback_prompt_path: "prompts/feedback.txt"
individual_summary_prompt: "prompts/integration/individual_summary_for_integration.txt"