analysis_mode: "report"
input_dirs:
  - "/home/joon/dev/critical_analyzer/data/conversation_math/"

# Report 모드 설정
report_types:
  - "student"
  - "teacher"

# 프롬프트 파일 경로
student_prompt_path: "prompts/report/report_student.txt"
teacher_prompt_path: "prompts/report/report_teacher.txt"

# 출력 설정
output_base_dir: "outputs/reports"
output_formats:
  - "md"
  - "pdf"

# 파일 처리 설정
file_patterns:
  folder_pattern: "(.+)_([a-f0-9]{8})"  # 이름_8자리ID 패턴
  chat_file_pattern: "chats_*.txt"      # chats_로 시작하는 txt 파일

# 버전 정보
version: "1.0"
description: "학생-AI 튜터 대화 분석을 위한 교육 리포트 생성 모드"