defaults:
  - llm: gemini_flash #openai_4o #gemini_pro #perplexity_sonar perplexity_sonar #
  - mode: integration # Default mode is integration
  - _self_

base_output_dir: "/home/joon/dev/critical_analyzer/outputs"
summaries_sub_dir: "Reports" # 개별 요약 파일이 저장될 하위 디렉토리
output_file: "comprehensive_report.md"
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys:
          - hydra

prompt:
  individual_summary_prompt: "prompts/individual_summary.txt"
